<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>BLOG</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="<?= HOME; ?>/">BLOG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= HOME; ?>/home">Home</a>
                </li>
                <?php if (\Blog\Session\Session::hasUserSession('user')) : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= HOME; ?>/categories">Categorias</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= HOME; ?>/posts">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= HOME; ?>/users">Usuários</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= HOME; ?>/auth/logout">Sair</a>
                    </li>
                <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= HOME; ?>/auth/login">Entrar</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </nav>
