<?php if (\Blog\Session\Session::hasKeySession('success')) : ?>
    <div class="alert alert-success">
        <?= \Blog\Session\Flash::returnMessageSession('success'); ?>
    </div>
<?php endif; ?>

<?php if (\Blog\Session\Session::hasKeySession('warning')) : ?>
    <div class="alert alert-warning">
        <?= \Blog\Session\Flash::returnMessageSession('warning'); ?>
    </div>
<?php endif; ?>

<?php if (\Blog\Session\Session::hasKeySession('danger')) : ?>
    <div class="alert alert-danger">
        <?= \Blog\Session\Flash::returnMessageSession('danger'); ?>
    </div>
<?php endif; ?>
