<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Página Inicial Do Painel</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" class="href">
    <style>
        .content {
            margin-top: 80px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="<?= HOME; ?>">Loja Admin</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <?php if (\LojaVirtual\Session\Session::hasUserSession('user')) : ?>
                        <li>
                            <a href="<?= HOME; ?>/admin/categories">Categorias</a>
                        </li>
                        <li>
                            <a href="<?= HOME; ?>/admin/products">Produtos</a>
                        </li>
                        <li>
                            <a href="<?= HOME; ?>/admin/users">Usuários</a>
                        </li>
                        <li>
                            <a href="<?= HOME; ?>/auth/logout">Deslogar</a>
                        </li>
                    <?php else : ?>
                        <li>
                            <a href="<?= HOME; ?>/">Ir para site</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
