<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    <h1>Editar Usuário</h1>
    <hr>
    <form method="POST" action="<?= HOME; ?>/categories/edit/<?=$this->category['id'];?>">
    <div class="form-group">
            <label for="name">Nome</label>
            <input type="text" class="form-control" id="name" value="<?=$this->category['name'];?>" name="name">
        </div>
        <div class="form-group">
            <label for="description">Descrição</label>
            <input type="text" class="form-control" id="description" value="<?=$this->category['description'];?>" name="description">
        </div>
        <button type="submit" class="btn btn-success">Salvar Alteração</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
