<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    <h1>Cadastrar Nova Categoria</h1>
    <hr>
    <form method="POST" action="<?= HOME; ?>/categories/new">
        <div class="form-group">
            <label for="name">Nome</label>
            <input type="text" class="form-control" id="name" placeholder="Nome do usuário" name="name">
        </div>
        <div class="form-group">
            <label for="description">Descrição</label>
            <input type="text" class="form-control" id="description" placeholder="Sobrenome do usuário" name="description">
        </div>
        <button type="submit" class="btn btn-success">Salvar Categoria</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
