<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <main role="main" class="container">
        <h1 class="mb-5">About</h1>
        <h2>A Instituição</h2>
        <div class="col-md-12">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Exercitationem beatae debitis quam sapiente totam voluptatem illo
            dolorum quis a praesentium delectus obcaecati alias, enim aliquam tempore.
            Excepturi recusandae earum nisi!
        </div>
        <div class="col-md-12">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Exercitationem beatae debitis quam sapiente totam voluptatem illo
            dolorum quis a praesentium delectus obcaecati alias, enim aliquam tempore.
            Excepturi recusandae earum nisi!
        </div>
        <h2>Nossas Metas</h2>
        <div class="col-md-12">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Exercitationem beatae debitis quam sapiente totam voluptatem illo
            dolorum quis a praesentium delectus obcaecati alias, enim aliquam tempore.
            Excepturi recusandae earum nisi!
        </div>
        <h2>Valores</h2>
        <div class="col-md-12">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Exercitationem beatae debitis quam sapiente totam voluptatem illo
            dolorum quis a praesentium delectus obcaecati alias, enim aliquam tempore.
            Excepturi recusandae earum nisi!
        </div>

</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
