<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <main role="main" class="container">
        <h1 class="mb-3">Entre em contato conosco</h1>
        <h2>Fale conosco</h2>
        <div class="col-md-12">
            Telefone: <a href="tel:9999999-9999"><strong>99 99999-9999</strong></a><br>
            E-mail: <a href="mailto:email@email.com"><strong>email@email.com</strong></a>
        </div>
        <p class="mt-4 mb-4">Ou fale através do formulário abaixo:</p>
        <form>
            <div class="form-group">
                <label for="name">Nome</label>
                <input type="text" class="form-control" id="name" placeholder="Nome completo" name="name">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" id="email" placeholder="Email para contato" name="email">
            </div>
            <div class="form-group">
                <label for="subject">Assunto</label>
                <input type="Text" class="form-control" id="subject" placeholder="Assunto" name="subject">
            </div>
            <div class="form-group">
                <label for="mensagem">Mensagem</label>
                <textarea name="message" id="" cols="30" rows="10" class="form-control"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Enviar Contato</button>
        </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
