<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
  <main role="main" class="container">
    <div class="jumbotron">
      <h1>Bem vindo ao Institucional do VEX</h1>
      <p class="lead">Projeto criado no curso de PHP Orientado a Objetos da Code Experts Learning.</p>
      <a class="btn btn-lg btn-primary" target="blank" href="https://codeexperts.com.br/" role="button">Saiba mais &raquo;</a>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
  crossorigin="anonymous"></script>
  <script>
    window.jQuery || document.write('<script src="/docs/4.6/assets/js/vendor/jquery.slim.min.js"><\/script>')
  </script>
  <script src="/docs/4.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" 
  crossorigin="anonymous"></script>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
