<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    <h1>Usuários - <small>Gerencie seus usuários</small> </h1>
    <a class="btn btn-warning" href="<?= HOME; ?>/users/new">Novo Usuário</a>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Sobrenome</th>
                <th>Criado em</th>
                <th>Ação</th>
            </tr>
        <tbody>
            <?php foreach ($this->users as $user) : ?>
                <tr>
                    <td><?= $user['id']; ?></td>
                    <td><?= $user['first_name']; ?></td>
                    <td><?= $user['last_name']; ?></td>
                    <td><?= date('d/m/Y H:i:s', strtotime($user['created_at'])); ?></td>
                    <td>
                        <a href="<?= HOME; ?>/users/edit/<?= $user['id']; ?>" class="btn btn-primary">Editar</a>
                        <a href="<?= HOME; ?>/users/remove/<?= $user['id']; ?>" class="btn btn-danger">Apagar</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        </thead>
    </table>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
