<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    <h1>Editar Post</h1>
    <hr>
    <form method="POST" action="<?= HOME; ?>/posts/edit/<?= $this->post['id']; ?>">
        <div class="form-group">
            <div class="form-group col-md-9">
                <label for="category_id">Categoria</label>
                <select name="category_id">
                    <option value="#">Selecione uma categoria</option>
                    <?php foreach ($this->categories as $category) : ?>
                        <option value="<?= $category['id']; ?>" <?php if ($this->post['category_id'] == $category['id']) : ?>selected<?php endif; ?>>
                            <?= $category['name']; ?></option>
                    <?php endforeach; ?>
                </select>
                <label class="ml-4" for="type">Tipo</label>
                <select name="type">
                    <option value="#">Selecione um tipo</option>
                    <option value="page" <?php if ($this->post['type'] == 'page') : ?>selected<?php endif; ?>>Page
                    </option>
                    <option value="post" <?php if ($this->post['type'] == 'post') : ?>selected<?php endif; ?>>Post
                    </option>
                </select>
                <label class="ml-4" for="type">Usuário</label>
                <select name="user_id">
                    <option value="#">Selecione o autor</option>
                    <?php foreach ($this->users as $user) : ?>
                        <option value="<?= $user['id']; ?>" <?php if ($this->post['user_id'] == $user['id']) : ?>selected<?php endif; ?>>
                            <?= $user['first_name'] . ' ' . $user['last_name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="title">Título</label>
            <input type="text" class="form-control" id="title" name="title" value="<?= $this->post['title']; ?>">
        </div>
        <div class="form-group">
            <label for="description">Descrição</label>
            <input type="text" class="form-control" id="description" name="description" value="<?= $this->post['description']; ?>">
        </div>
        <div class="form-group">
            <label for="content">Conteúdo</label>
            <textarea name="content" id="content" cols="30" rows="8" class="form-control"><?= $this->post['content']; ?></textarea>
        </div>
        <button type="submit" class="btn btn-success">Salvar Alteração</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
