<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="row">
    <div class="col-md-12">
        <h2 class="alert alert-success mt-5 text-center">Muito obrigado por sua compra! ;) </h2>
    </div>
</div>
<div class="row ">
    <div class="col-md-12">
    <h4 class="text-center">Sua compra foi registrada com sucesso! Código de referência:
        <span class="text-danger font-weight-bold"><?= $this->reference[0] ?></span></h4>
    </div>
</div>

<?php require VIEWS_PATH . '/includes/footer.phtml'; ?>
