<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <h1>Editar despesa</h1>
    <hr>
    <form method="POST" action="<?= HOME; ?>/expenses/edit/<?= $this->expense['id']; ?>">
        <div class="form-group">
            <label for="category_id">Categoria</label>
            <select name="category_id">
                <?php foreach ($this->categories as $category) : ?>
                    <option value="<?= $category['id']; ?>"><?= $category['name']; ?>
                        <?php if ($category['id'] == $this->expense['category_id']) : ?>

                        <?php endif; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
        </div>
        <div class="form-group">
            <label for="value">Valor Gasto</label>
            <input type="text" class="form-control" id="value" placeholder="Valor gasto" name="value" value="<?= $this->expense['value']; ?>">
        </div>
        <div class="form-group">
            <label for="description">Descrição</label>
            <textarea name="description" id="description" cols="30" rows="8" class="form-control"><?= $this->expense['description']; ?></textarea>
        </div>
        <button type="submit" class="btn btn-success">Atualizar Despensa</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
