<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <h1>Cadastrar nova despesa</h1>
    <hr>
    <form method="POST" action="<?= HOME; ?>/expenses/new">
        <div class="form-group">
            <label for="category_id">Categoria</label>
            <select name="category_id">
                <?php foreach ($this->categories as $category) : ?>
                    <option value="<?= $category['id']; ?>"><?= $category['name']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <label for="value">Valor Gasto</label>
            <input type="text" class="form-control" id="value" placeholder="Valor gasto" name="value">
        </div>
        <div class="form-group">
            <label for="description">Descrição</label>
            <textarea name="description" id="description" cols="30" rows="8" class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Salvar Despensa</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
