<?php require VIEWS_PATH . '/admin/includes/header.phtml'; ?>

<div class="container">
    <div class="row">
        <div class="class col-md-12">
            <h2>Editar Produto</h2>
            <hr>
        </div>
    </div>
    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>
    <form action="<?= HOME . '/admin/products/edit/' . $this->product['id']; ?>" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Nome do produto</label>
                    <input type="text" class="form-control" name="name" value="<?= $this->product['name']; ?>">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Descrição do produto</label>
                    <input type="text" class="form-control" name="description" value="<?= $this->product['description']; ?>">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="">Preço</label>
                        <input type="text" class="form-control" name="price" value="<?= number_format($this->product['price'], 2, ',', '.'); ?>">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="">Status Produto</label>
                        <select name="is_active" id="" class="form-control">
                            <option value="A" <?php if ($this->product['is_active']) : ?> selected <?php endif; ?>>Ativo</option>
                            <option value="I" <?php if (!$this->product['is_active']) : ?> selected <?php endif; ?>>Inativo</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Conteúdo do produto</label>
                    <input type="text" class="form-control" name="content" value="<?= $this->product['content']; ?>">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Selecione as imagens do produto</label>
                    <input type="file" class="form-control" name="images[]" multiple>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="">Status Produto</label>
                <select name="categories[]" id="" class="form-control" multiple>
                    <?php foreach ($this->categories as $category) : ?>
                        <option value="<?= $category['id']; ?>" <?php if (in_array($category['id'], $this->productCategories)) : ?> selected <?php endif; ?>>
                            <?= $category['name']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row">
                <button type="submit" class="btn btn-success">Atualizar Produto</button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-md-12">
            <h2>Imagens do Produto</h2>
            <hr>
        </div>
        <?php foreach ($this->product['images'] as $key => $image) : ?>
            <div class="col-md-3 static-center">
                <img src="<?= HOME; ?>/uploads/products/<?= $image['image']; ?>" alt="Imagem do produto <?= $this->product['name']; ?>" class="img-responsive">
                <a href="<?= HOME; ?>/admin/images/remove/<?= $image['id']; ?>" class="btn-sm btn-danger">X</a>
            </div>
            <?php if (($key + 1) % 3 == 0) : ?>
    </div>
    <div class="row">
    <?php endif; ?>
    <?php endforeach; ?>
    </div>
</div>

<?php require VIEWS_PATH . '/admin/includes/footer.phtml'; ?>
