<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Projeto Final - Loja Virtual</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" class="href">
    <script src="https://use.fontawesome.com/f67fbade71.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark mb-3">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#"> Experts Learning Store</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="<?= HOME; ?>/" class="nav-link">Home</a>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <div class="float-right">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="<?=HOME;?>/cart" class="nav-link">
                    <?php if(\LojaVirtual\Session\Session::hasUserSession('cart')) : ?>
                        <span class="bagge badge-danger">
                            <?= count(\LojaVirtual\Session\Session::verifyExistsKeyAndAddInCart('cart')) ;?>
                        </span>
                    <?php endif;?>
                        <i class="fa fa-2x fa-shopping-cart"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!--/.container-fluid -->
    </nav>
    <div class="container">
