<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">

    <main role="main" class="container">

        <div class="jumbotron">

            <h1>Gerenciador de Gastos Pessoais</h1>

            <p class="lead">Projeto criado no curso de PHP Orientado a Objetos da Code Experts Learning.</p>

            <a class="btn btn-lg btn-primary" target="blank" href="https://codeexperts.com.br/" role="button">Saiba mais &raquo;</a>
        </div>

        <div class="col-md-12">

        </div>

    </main>

</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
