<?php if (\LojaVirtual\Session\Session::hasUserSession('success')) : ?>
    <div class="alert alert-success">
        <?= \LojaVirtual\Session\Flash::returnMessageSession('success'); ?>
    </div>
<?php endif; ?>

<?php if (\LojaVirtual\Session\Session::hasUserSession('warning')) : ?>
    <div class="alert alert-warning">
        <?= \LojaVirtual\Session\Flash::returnMessageSession('warning'); ?>
    </div>
<?php endif; ?>


<?php if (\LojaVirtual\Session\Session::hasUserSession('danger')) : ?>
    <div class="alert alert-danger">
        <?= \LojaVirtual\Session\Flash::returnMessageSession('danger'); ?>
    </div>
<?php endif; ?>
