<?php require VIEWS_PATH . '/admin/includes/header.phtml'; ?>

<div class="container">
    <div class="row">
        <div class="class col-md-12">
            <h2>Criar Produto</h2>
            <hr>
        </div>
    </div>
    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>
    <form action="<?= HOME . '/admin/products/new'; ?>" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Nome do produto</label>
                    <input type="text" class="form-control" name="name">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Descrição do produto</label>
                    <input type="text" class="form-control" name="description">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="">Preço</label>
                        <input type="text" class="form-control" name="price">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="">Status Produto</label>
                        <select name="is_active" id="" class="form-control">
                            <option value="A">Ativo</option>
                            <option value="I">Inativo</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Conteúdo do produto</label>
                    <input type="text" class="form-control" name="content">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="class col-md-12">
                <div class="form-group">
                    <label for="">Selecione as imagens do produto</label>
                    <input type="file" class="form-control" name="images[]" multiple>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="">Selecione as categorias</label>
                <select name="categories[]" id="" multiple class="form-control">
                    <?php foreach ($this->categories as $category) : ?>
                        <option value="<?= $category['id']; ?>">
                            <?= $category['name']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row">
                <button type="submit" class="btn btn-success">Salvar Produto</button>
            </div>
        </div>
    </form>
</div>

<?php require VIEWS_PATH . '/admin/includes/footer.phtml'; ?>
